### PR TITLE
Descriptional Optional

### LINKED ISSUE #4: Make Description Optional on Personal Schedule
Currently, the description field on personal schedule is required.

Make it optional.

### PR DESCRIPTION
**Pull request by raychen179**
Description is now optional + created unit test for create page
Dokku Deployment: https://desc-opt.dokku-01.cs.ucsb.edu/

Closes #4

### CODE REVIEW

**Review by vincentc0202 — APPROVED** [review]
Good changes

**Review by pconrad — APPROVED** [review]
LGTM

**Comment by raychen179** [comment]
Dokku Deployment: https://desc-opt.dokku-01.cs.ucsb.edu/

**Review by raysujf — APPROVED** [review]
LGTM

**Review by pconrad — APPROVED** [review]
LGTM.. will test on dokku.

**Pull request merged**
